### ISSUE TITLE
OneInchEye Camera Interface Board for CM4 

### ISSUE THREAD

**Issue by amits26** [will127534/OneInchEye#5]
Hi,

I am really interested to build oneincheye camera for my telescope and I working on sourcing PCB from JLCPCB as oneincheye is out of stock. Only concern I am having now is not able to find any baseboard for CM4 with 22Pin CSI interface. I don't want to go with CM4 I/O board which is bulky and looks to be only option for 22Pin CSI connector. There are some base boards with 15pin CSI connectors like PiCam Module for Raspberry Pi Compute Module 4 but again with 15Pin CSI connector. I don't think 15pin is right choice looking at your design. is there any other way to connect oneincheye camera module to CM4 without making it bulky ?

Thanking in advance.

Amit

**Comment by will127534** [comment]
Yeah that is also the reason why I've build my own CM4 camera board with 22pin 4-lane MIPI connector.
No way other then building yourself one because it is rare for anyone building a CM4 baseboard for almost non existent camera modules.
Another easier option will be using RPI5 directly, which I've been working on updating the driver. Moreover you get the bonus of having PCIe 3.0 x1 connector for faster drive speed if you are planning for planetary Imaging.
